# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/project
spring.datasource.username=myuser
spring.datasource.password=Admin@123

#spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/project
#spring.datasource.username=SYfVSnSTXtz1HqM.root
#spring.datasource.password=2YNBTtcxmhWFiZWu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# JPA
# ===============================
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JWT
# ===============================
jwt.secret=artisan-ecommerce-secret-key-256-bit
jwt.expiration=86400000

# ===============================
# CORS
# ===============================
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allow-credentials=true

# ===============================
# GOOGLE OAUTH
# ===============================
spring.security.oauth2.client.registration.google.client-id=xxxxxx
spring.security.oauth2.client.registration.google.client-secret=xxxxx
spring.security.oauth2.client.registration.google.scope=email,profile
